"""Added new token_blacklist table

Revision ID: 09f6d4b45a45
Revises: 6d7e61d31a65
Create Date: 2025-12-02 21:29:02.905984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f6d4b45a45'
down_revision: Union[str, Sequence[str], None] = '6d7e61d31a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
