"""change column setting in Advertisement table

Revision ID: 6d7e61d31a65
Revises: 574d6fddd168
Create Date: 2025-10-30 13:21:04.613210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7e61d31a65'
down_revision: Union[str, Sequence[str], None] = '574d6fddd168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if constraint exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    constraints = [c['name'] for c in inspector.get_unique_constraints('ad_content')]
    if 'ad_content_ad_type_key' in constraints:
        op.drop_constraint(op.f('ad_content_ad_type_key'), 'ad_content', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('ad_content_ad_type_key'), 'ad_content', ['ad_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
