"""Added new column otp verified to Session table

Revision ID: ecd2b8657371
Revises: 09f6d4b45a45
Create Date: 2025-12-05 19:23:46.112633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd2b8657371'
down_revision: Union[str, Sequence[str], None] = '09f6d4b45a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'token_blacklist' not in tables:
        op.create_table('token_blacklist',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    # Check if column exists before adding
    columns = [c['name'] for c in inspector.get_columns('session_data')]
    if 'otp_is_verified' not in columns:
        op.add_column('session_data', sa.Column('otp_is_verified', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_data', 'otp_is_verified')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
