FROM rasa/rasa-sdk:3.6.2
WORKDIR /app
COPY .  /app
USER root
RUN pip install --upgrade pip \
    && pip3 install -r actions/action_requirements.txt
RUN cd actions
EXPOSE 5055
CMD ["start", "--debug", "--port", "5055", "--cors", "*", "--actions", "actions"]
